# Generated by Django 5.2.15 on 2026-06-25 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('tickets', '0002_ticket_classification_reason_ticket_classified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('reply_draft', 'Reply Draft'), ('summary', 'Summary'), ('priority', 'Priority'), ('intent', 'Intent'), ('next_action', 'Next Action'), ('macro', 'Macro')], max_length=32)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('edited', 'Edited'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='proposed', max_length=32)),
                ('content', models.TextField()),
                ('internal_notes', models.TextField(blank=True)),
                ('needs_approval', models.BooleanField(default=False)),
                ('proposed_sensitive_action', models.CharField(blank=True, max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=64)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_by_ai', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_copilot_suggestions', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_copilot_suggestions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrievedContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('content_snapshot', models.TextField()),
                ('source_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_contexts', to='knowledge_base.knowledgechunk')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_contexts', to='copilot.copilotsuggestion')),
            ],
            options={
                'ordering': ['relevance_score', 'id'],
            },
        ),
    ]
