# Generated by Django 5.2.15 on 2026-06-25 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copilot', '0001_initial'),
        ('tickets', '0002_ticket_classification_reason_ticket_classified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('refund', 'Refund'), ('cancellation', 'Cancellation'), ('account_closure', 'Account Closure'), ('credit_adjustment', 'Credit Adjustment'), ('data_export', 'Data Export'), ('data_deletion', 'Data Deletion'), ('support_lead_review', 'Support Lead Review')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('reason', models.TextField()),
                ('proposed_payload', models.JSONField(blank=True, default=dict)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='copilot.copilotsuggestion')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
