# Generated by Django 5.2.15 on 2026-06-26 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copilot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'OK'), (4, 'Good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True)),
                ('failure_tag', models.CharField(blank=True, choices=[('inaccurate', 'Inaccurate'), ('wrong_policy', 'Wrong Policy'), ('missing_context', 'Missing Context'), ('unsafe_action', 'Unsafe Action'), ('tone_issue', 'Tone Issue'), ('too_long', 'Too Long'), ('too_short', 'Too Short'), ('hallucinated', 'Hallucinated'), ('pii_problem', 'PII Problem')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='copilot.copilotsuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('suggestion', 'user'), name='unique_feedback_per_suggestion_user')],
            },
        ),
    ]
