# Generated by Django 5.2.15 on 2026-06-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='classification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='needs_escalation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sentiment',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
