# Generated by Django 5.2.15 on 2026-06-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dataset_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=128)),
                ('classifier_f1', models.FloatField(default=0.0)),
                ('escalation_precision', models.FloatField(default=0.0)),
                ('escalation_recall', models.FloatField(default=0.0)),
                ('groundedness_score', models.FloatField(default=0.0)),
                ('average_latency_ms', models.FloatField(default=0.0)),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('failed_cases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
